//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.05 at 06:19:25 PM MSK 
//


package ru.telda._01.integration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Card112Result" type="{http://www.telda.ru/01/integration}Card112Result" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "card112Result"
})
@XmlRootElement(name = "Card112Response")
public class Card112Response {

    @XmlElement(name = "Card112Result")
    protected Card112Result card112Result;

    /**
     * Gets the value of the card112Result property.
     * 
     * @return
     *     possible object is
     *     {@link Card112Result }
     *     
     */
    public Card112Result getCard112Result() {
        return card112Result;
    }

    /**
     * Sets the value of the card112Result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Card112Result }
     *     
     */
    public void setCard112Result(Card112Result value) {
        this.card112Result = value;
    }

}
